allen_metadata: "resources/van_allen_METADATA.csv"
allen_SRR: "Run"
allen_sample_id: "Run"
hugo_metadata: "resources/hugo_METADATA.csv"
hugo_SRR: "Run"
hugo_sample_id: "Run"
ngc_file: "/home/tof4003/ngckey.ngc"
tmpdir: "/athena/nixonlab/scratch/tof4003/Mets_CM_bulk_tmp"
fastq_mem_mb: 150000
star_align_multi:
    genomeDir: "resources/STAR_gdc38_gencode38"
    outFilterMultimapNmax: 200
    winAnchorMultimapNmax: 200
telescope:
    annotation: "resources/retro.hg38.v1.gtf"
genome_fasta: "resources/GRCh38.d1.vd1.fa"
annotation_gtf: "resources/gencode.v38.annotation.gtf"
ega_credentials: "$HOME/.egaconfig"
tmp: "/athena/nixonlab/scratch/tof4003/TCGA-SKCM_tmp"